<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title> 11 Régression | Méthodes Quantitatives avec R</title>
<meta name="author" content="P.-O. Caron">
<meta name="description" content="L’objectif de la régression est de décrire la relation entre un variable dépendante et un ensemble de variables indépendantes. Une première méthode de mesure d’association est la covariance (vue...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content=" 11 Régression | Méthodes Quantitatives avec R">
<meta property="og:type" content="book">
<meta property="og:url" content="mqr.teluq.ca/régression.html">
<meta property="og:description" content="L’objectif de la régression est de décrire la relation entre un variable dépendante et un ensemble de variables indépendantes. Une première méthode de mesure d’association est la covariance (vue...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content=" 11 Régression | Méthodes Quantitatives avec R">
<meta name="twitter:description" content="L’objectif de la régression est de décrire la relation entre un variable dépendante et un ensemble de variables indépendantes. Une première méthode de mesure d’association est la covariance (vue...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body>
<p>
    \(
    \newcommand{\EX}{\mathbb{E}}
    \)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="bs4_style.css"></p>

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Méthodes Quantitatives avec R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Bienvenue!</a></li>
<li><a class="" href="pr%C3%A9face.html">Préface</a></li>
<li class="book-part">Rudiments</li>
<li><a class="" href="commencer.html"><span class="header-section-number">1</span> Commencer</a></li>
<li><a class="" href="programmer.html"><span class="header-section-number">2</span> Programmer</a></li>
<li><a class="" href="calculer.html"><span class="header-section-number">3</span> Calculer</a></li>
<li><a class="" href="exercice-rudiments.html">Exercices</a></li>
<li class="book-part">Jeux de données</li>
<li><a class="" href="g%C3%A9rer.html"><span class="header-section-number">4</span> Gérer</a></li>
<li><a class="" href="importer.html"><span class="header-section-number">5</span> Importer</a></li>
<li><a class="" href="manipuler.html"><span class="header-section-number">6</span> Manipuler</a></li>
<li><a class="" href="visualiser.html"><span class="header-section-number">7</span> Visualiser</a></li>
<li><a class="" href="exercice-gestion.html">Exercices</a></li>
<li class="book-part">La statistique</li>
<li><a class="" href="inf%C3%A9rer.html"><span class="header-section-number">8</span> Inférer</a></li>
<li><a class="" href="analyser.html"><span class="header-section-number">9</span> Analyser</a></li>
<li><a class="" href="simuler.html"><span class="header-section-number">10</span> Simuler</a></li>
<li><a class="" href="exercice-analyse.html">Exercices</a></li>
<li class="book-part">Analyses statistiques</li>
<li><a class="active" href="r%C3%A9gression.html"><span class="header-section-number">11</span> Régression</a></li>
<li><a class="" href="cr%C3%A9er.html"><span class="header-section-number">12</span> Créer</a></li>
<li><a class="" href="solutions.html">Solutions</a></li>
<li><a class="" href="r%C3%A9f%C3%A9rences.html">Références</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/quantmeth/MQR">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="régression" class="section level1" number="11">
<h1>
<span class="header-section-number"> 11</span> Régression<a class="anchor" aria-label="anchor" href="#r%C3%A9gression"><i class="fas fa-link"></i></a>
</h1>
<p>L’objectif de la régression est de décrire la relation entre un variable dépendante et un ensemble de variables indépendantes. Une première méthode de mesure d’association est la covariance (vue dans le chapitre sur les analyses de base) qui est représentée par l’équation ci-dessous.</p>
<p><span class="math display" id="eq:cov1">\[\begin{equation}
s_{xy}=\frac{1}{n-1}\sum_{i=1}^n(x_i-\bar{x})(y_i-\bar{y})
\tag{11.1}
\end{equation}\]</span></p>
<p>L’équation <a href="r%C3%A9gression.html#eq:cov1">(11.1)</a> représente la somme des produits des écarts à la moyenne de deux variables. Comment généraliser cette équation à un ensemble de plus de deux variables? Pour débuter, les variables sont mises sur un même pied d’égalité, plutôt que de recourir à des lettres différentes (<span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>), elles sont toutes considérées comme des <span class="math inline">\(x_{i,j}\)</span>, où l’indice <span class="math inline">\(i\)</span> identifie le <span class="math inline">\(i\)</span><sup>e</sup> participant, comme pour l’équation <a href="r%C3%A9gression.html#eq:cov1">(11.1)</a>, et l’indice <span class="math inline">\(j\)</span> indique la <span class="math inline">\(j\)</span><sup>e</sup> variable parmi <span class="math inline">\(p\)</span>. Le calcul pour chacune des paires de variables <span class="math inline">\(j\)</span> et <span class="math inline">\(k\)</span> est réalisé pour les <span class="math inline">\(p\)</span> variables; l’équation de la covariance devient ainsi.</p>
<p><span class="math display" id="eq:cov2">\[\begin{equation}
s_{x_j,x_k}=\frac{1}{n-1}\sum_{i=1}^n(x_{i,j}-\bar{x_j})(x_{i,k}-\bar{x_k})
\tag{11.2}
\end{equation}\]</span></p>
<p>Si les variables sont centrées, l’équation <a href="r%C3%A9gression.html#eq:cov2">(11.2)</a> devient, pour faciliter l’intuition, l’équation <a href="r%C3%A9gression.html#eq:cov3">(11.3)</a>, soit la somme des produits entre deux variables.</p>
<p><span class="math display" id="eq:cov3">\[\begin{equation}
s_{x_j,x_k}=\frac{1}{n-1}\sum_{i=1}^n(x_{i,j})(x_{i,k})
\tag{11.3}
\end{equation}\]</span></p>
<p>Avantageusement, lorsque <span class="math inline">\(j=k\)</span>, les équations <a href="r%C3%A9gression.html#eq:cov2">(11.2)</a> et <a href="r%C3%A9gression.html#eq:cov3">(11.3)</a> calculent la variance de la variable correspondante. En syntaxe <strong>R,</strong> ces équations pourraient s’écrire dans une fonction comme la suivante. Pour rappel, la fonction <code><a href="https://rdrr.io/r/stats/cor.html">cov()</a></code> dans laquelle une matrice de données est passée comme argument fournira la matrice de covariance.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="r%C3%A9gression.html#cb134-1" aria-hidden="true" tabindex="-1"></a>covariance1 <span class="ot">&lt;-</span> <span class="cf">function</span>(X){} </span>
<span id="cb134-2"><a href="r%C3%A9gression.html#cb134-2" aria-hidden="true" tabindex="-1"></a><span class="co"># X est un jeu de données</span></span>
<span id="cb134-3"><a href="r%C3%A9gression.html#cb134-3" aria-hidden="true" tabindex="-1"></a>Xc <span class="ot">=</span> X <span class="sc">-</span> <span class="fu">colMeans</span>(X) <span class="co"># Centrées les variables</span></span>
<span id="cb134-4"><a href="r%C3%A9gression.html#cb134-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">dim</span>(X)[<span class="dv">2</span>]    <span class="co"># Nombre de variables </span></span>
<span id="cb134-5"><a href="r%C3%A9gression.html#cb134-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">dim</span>(X)[<span class="dv">1</span>]    <span class="co"># Nombre de sujets</span></span>
<span id="cb134-6"><a href="r%C3%A9gression.html#cb134-6" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> <span class="fu">as.numeric</span>() <span class="co"># Matrice vide pour enregistrer résultats (Sigma)</span></span>
<span id="cb134-7"><a href="r%C3%A9gression.html#cb134-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>p) {</span>
<span id="cb134-8"><a href="r%C3%A9gression.html#cb134-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>p) {</span>
<span id="cb134-9"><a href="r%C3%A9gression.html#cb134-9" aria-hidden="true" tabindex="-1"></a>    S <span class="ot">=</span> <span class="fu">sum</span>(Xc[,j] <span class="sc">*</span> Xc[,k])</span>
<span id="cb134-10"><a href="r%C3%A9gression.html#cb134-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb134-11"><a href="r%C3%A9gression.html#cb134-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb134-12"><a href="r%C3%A9gression.html#cb134-12" aria-hidden="true" tabindex="-1"></a>S <span class="ot">=</span> S <span class="sc">/</span> (n<span class="dv">-1</span>)</span>
<span id="cb134-13"><a href="r%C3%A9gression.html#cb134-13" aria-hidden="true" tabindex="-1"></a><span class="co"># S est la matrice de covariance</span></span>
<span id="cb134-14"><a href="r%C3%A9gression.html#cb134-14" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(<span class="at">covariance =</span> S)</span>
<span id="cb134-15"><a href="r%C3%A9gression.html#cb134-15" aria-hidden="true" tabindex="-1"></a><span class="er">}</span></span></code></pre></div>
<p>Dans le code <strong>R</strong> ci-joint, <code><a href="https://rdrr.io/r/base/dim.html">dim()</a></code> extrait le nombre de dimensions de la base de données, soit le nombre d’unités et le nombre de variables. Les crochets dans l’expression <code>dim(X)[1]</code> indiquent que seule la première valeur doit être enregistrée - le nombre d’unités et <code>dim(X)[2]</code>, le nombre de variable. Il est possible d’utiliser cette astuce dans d’autres contextes. La fonction <code><a href="https://rdrr.io/r/base/colSums.html">colMeans()</a></code> (moyenne de chaque colonne) calcule toutes les moyennes des variables. La ligne soustrait de <code>X</code> ces moyennes.</p>
<div id="illustration-de-la-covariance" class="section level3" number="11.0.1">
<h3>
<span class="header-section-number">11.0.1</span> Illustration de la covariance<a class="anchor" aria-label="anchor" href="#illustration-de-la-covariance"><i class="fas fa-link"></i></a>
</h3>
<p>Il est relativement aisé d’exprimer graphiquement la covariance bivariée. Pour chaque paire <span class="math inline">\((x_i,y_i)\)</span>, il est possible de dessiner un rectangle à partir du centre <span class="math inline">\((0, 0)\)</span>. Lorsque la moyenne d’une variable est soustraite, les données deviennent centrées sur ce point. L’expression <span class="math inline">\(xy\)</span> ou <span class="math inline">\(x_ix_j\)</span> peut rappeler à certain le calcul de l’aire d’un rectangle. C’est effectivement ce qui se produit pour la covariance. L’équation calcule l’aire du rectangle formé par les points <span class="math inline">\((0,0)\)</span> et <span class="math inline">\((x_i,y_i)\)</span>. En fait, la covariance calcule le rectangle <em>moyen</em>, car le produit est ensuite divisé par le nombre de rectangles <span class="math inline">\((-1)\)</span>.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="06-Regression_files/figure-html/unnamed-chunk-2-1.png" alt="Illustration de la covariance" width="75%" height="75%"><p class="caption">
Figure 11.1: Illustration de la covariance
</p>
</div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="06-Regression_files/figure-html/unnamed-chunk-3-1.png" alt="Illustration des produits (rectangles) pour différentes valeurs de covariance" width="672"><p class="caption">
Figure 11.2: Illustration des produits (rectangles) pour différentes valeurs de covariance
</p>
</div>
<p>À partir des images suivantes, quelques propriétés de la covariance peuvent être déduites.</p>
<ul>
<li><p>Comme la quantité de surface blanche (ou de noire) dépend de la taille de la figure, la covariance est directement proportionnelle aux échelles à l’abscisse et l’ordonnée.</p></li>
<li><p>La covariance augmente lorsque les points s’approchent d’une ligne à pente ascendante et diminue lorsque les points s’approchent d’une ligne à pente descendante.</p></li>
<li><p>Comme les associations non linéaires peuvent créer des amalgames de rectangles positifs et négatifs, elles conduisent à des covariances imprévisibles et peu pertinentes.</p></li>
<li><p>La covariance (et la corrélation) est sensible aux valeurs aberrantes. Un point éloigné de la masse créera une aire rectangulaire bien plus grande que les autres points. À lui seul, il peut créer une quantité substantielle positive ou négative de surface blanche (ou noire) dans la figure.</p></li>
<li><p>Si une variable est multipliée par elle-même, il s’agit de l’aire d’un carré, ce qui équivaut au calcul d’une variance. Par extension, si le produit de deux variables se rapproche davantage d’un carré que d’un rectangle (en moyenne), alors les deux variables sont fortement liées.</p></li>
<li><p>Le paramètre de la corrélation de la population peut être conceptualisé comme un triangle déformé en rectangle à cause de l’erreur de mesure des axes.</p></li>
</ul>
</div>
<div id="la-covariance-en-termes-dalgèbre-matricielle" class="section level3" number="11.0.2">
<h3>
<span class="header-section-number">11.0.2</span> La covariance en termes d’algèbre matricielle<a class="anchor" aria-label="anchor" href="#la-covariance-en-termes-dalg%C3%A8bre-matricielle"><i class="fas fa-link"></i></a>
</h3>
<p>Pour l’instant, seul l’aspect linéaire est présenté. L’équation de la covariance peut aussi se calculer en termes d’algèbre matricielle. En plus d’accélérer le calcul des résultats, il simplifie énormément les mathématiques sous-jante (pourvu que l’utilisateur connaisse l’algèbre matricielle).</p>
<p>Dans le présent contexte, une matrice est un ensemble de variables représentées sous une seule variables. Dans les équations mathématiques, une matrice est désignée par une lettre majuscule : <span class="math inline">\(x\)</span> devient <span class="math inline">\(X\)</span> et <span class="math inline">\(\sigma\)</span> devient <span class="math inline">\(Sigma\)</span>. Dans une matrice, chaque colonne est une variable, chaque ligne correspond à un sujet différent mesuré sur toutes les variables. Une matrice est définie en partie par son nombre de lignes (<span class="math inline">\(n\)</span>, nombre d’unités) et son nombre de colonnes (<span class="math inline">\(p\)</span>, nombre de variables), dont voici une illustration.</p>
<p><span class="math display">\[
X = \left(\begin{array}{cccc}
x_{1,1} &amp; x_{1,2} &amp; ...&amp;x_{1,p}\\
x_{2,1} &amp; x_{2,2} &amp; ...&amp;x_{2,p}\\
... &amp; ...&amp; ...&amp; ... \\
x_{n,1} &amp; x_{n,2} &amp; ... &amp;x_{n,p}\\
\end{array}\right)
\]</span></p>
<p>En syntaxe <strong>R</strong>, il ne s’agit rien de plus que de concaténer des variables (mesurant les mêmes individus) ensembles par des colonnes, comme il est fait avec des jeux de données <code><a href="https://rdrr.io/r/base/data.frame.html">data.frame()</a></code> ou <code><a href="https://rdrr.io/r/base/cbind.html">cbind()</a></code>. Un jeu de données est, à peu de chose près, une matrice. Pour créer une matrice <code>X</code> à partir des variables <code>x</code>, <code>y</code>, et <code>z</code> avec <strong>R</strong>, par exemple, la ligne <code>X = cbind(x, y, z)</code> joindra les trois variables ensemble.</p>
<p>Pour réaliser le calcul de la covariance, il faut multiplier la matrice des données centrées (les variables concaténées) par elle-même puis de diviser par <span class="math inline">\(n-1\)</span>. Le symbole <span class="math inline">\(X\)</span> représente la concaténation des variables. Par simplicité, l’équation utilise des <strong>variables centrées</strong>.</p>
<p><span class="math display" id="eq:covmat1">\[\begin{equation}
\Sigma = (n-1)^{-1}X^\prime X
\tag{11.4}
\end{equation}\]</span></p>
<p>Le symbole <span class="math inline">\(\Sigma\)</span> (sigma majuscule) représente la matrice de variance-covariance. La diagonale de cette matrice représente les variances des données et les éléments hors diagonales sont les covariances, soulignant le lien entre la variance et la covariance. Le symbole <span class="math inline">\(\prime\)</span> (prime) correspond à l’opération de transposer une matrice, soit d’échanger les lignes par ces colonnes. Cette procédure est nécessaire pour produire la multiplication d’une matrice par elle-même. Noter que l’expression <span class="math inline">\((n-1)^{-1}=\frac{1}{n-1}\)</span>.</p>
<p>TODO</p>
<p><span class="math display" id="eq:covmat2">\[\begin{equation}
\begin{align}
S &amp; = (n-1)^{-1}
\left(\begin{array}{cccc}
x_{1,1} &amp; x_{2,1} &amp; ... &amp; x_{n,1} \\
x_{2,1} &amp; x_{2,2} &amp; ... &amp; x_{n,2} \\
\end{array}\right)
\left(\begin{array}{cc}
x_{1,1} &amp; x_{1,2} \\
x_{2,1} &amp; x_{2,2}\\
... &amp; ...  \\
x_{n,1} &amp; x_{n,2} \\
\end{array}\right) \\
   &amp; = (n-1)^{-1}
\left(\begin{array}{cc}
\sum_{i=1}^n(x_{i,1})(x_{i,1}) &amp; \sum_{i=1}^n(x_{i,1})(x_{i,2})\\
\sum_{i=1}^n(x_{i,2})(x_{i,1}) &amp; \sum_{i=1}^n(x_{i,2})(x_{i,2})
\end{array}\right)
\end{align}
\tag{11.5}
\end{equation}\]</span></p>
<p>L’équation <a href="r%C3%A9gression.html#eq:covmat2">(11.5)</a> illustre l’équation <a href="r%C3%A9gression.html#eq:covmat1">(11.4)</a> qui sont toutes les deux équivalentes à <a href="r%C3%A9gression.html#eq:cov3">(11.3)</a>. En termes de syntaxe <strong>R</strong>, elles peuvent être traduites comme suit.</p>
<div class="sourceCode" id="cb135"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">covariance2</span> <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">{</span>
  <span class="co"># X est une data.frame ou matrice de n sujets par p variables</span>
  <span class="va">n</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>
  <span class="va">Xc</span> <span class="op">=</span> <span class="va">X</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span>
  <span class="co"># Algèbre matriciel pour le produit qui permet de calculer</span>
  <span class="co"># le produit d'une colonne avec les autres colonnes</span>
  <span class="va">cov.X</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">Xc</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">Xc</span> <span class="op">/</span> <span class="op">(</span><span class="va">n</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span>
  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">cov.X</span><span class="op">)</span>
<span class="op">}</span></code></pre></div>
<p>La fonction <code><a href="https://rdrr.io/r/base/t.html">t()</a></code> opère la transpose (<span class="math inline">\(\prime\)</span>) et le symbole <code>%*%</code> signifie le produit matriciel des variables. Si l’usuel symbole de multiplication <code>*</code> était utilisé, <strong>R</strong> opérerait une multiplication cellule par cellule (avec recyclage) plutôt que celle désirée ici.</p>
<p>L’utilisation de l’algèbre matricielle est plus simple et efficace : Elle nécessite cinq lignes de code, élimine deux boucles, prend moins de temps à calculer en plus de produire toutes les variances et les covariances.</p>
<p>Une matrice de covariance possède plusieurs propriétés qu’il faut connaître. Elle est toujours carrée soit <span class="math inline">\(p \times p\)</span> pour <span class="math inline">\(p\)</span> variables et contient <span class="math inline">\(p^2\)</span> éléments. Parmi ces éléments, les <span class="math inline">\(p\)</span> éléments de la diagonale sont des variances, ce pourquoi elle est parfois appelée matrice de variance-covariance. Les éléments triangulaires inférieurs hors diagonale sont un parfait reflet des éléments supérieurs, p.ex. <span class="math inline">\(\sigma_{1,2} = \sigma_{2,1}\)</span>. Il y a ainsi <span class="math inline">\(\frac{p(p-1)}{2}\)</span> covariances uniques dans une matrice et <span class="math inline">\(p(p+1)/2\)</span> éléments uniques (variances et covariances). En plus, de ces caractéristiques, la matrice doit être <em>positive semi-définie</em>, ce qui est un terme mathématique impliquant, pour les fins de ce chapitre, que les variances ne peuvent être nulles. (C’est plus complexe que cela, mais il suffit d’accepter cette affirmation pour procéder.)</p>
<p><span class="math display">\[
\Sigma = \left(
\begin{array}{cccc}
\sigma_{1,1} &amp; \sigma_{1,2} &amp; ... &amp;  \sigma_{1,p}\\
\sigma_{2,1} &amp; \sigma_{2,2} &amp; ... &amp;  \sigma_{2,p}\\
...&amp; ...&amp; ... &amp;  \sigma_{3,p}\\
\sigma_{p,1} &amp; \sigma_{p,2} &amp; ... &amp;  \sigma_{p,p}\\
\end{array}
\right)
\]</span></p>
</div>
<div id="création-de-données" class="section level3" number="11.0.3">
<h3>
<span class="header-section-number">11.0.3</span> Création de données<a class="anchor" aria-label="anchor" href="#cr%C3%A9ation-de-donn%C3%A9es"><i class="fas fa-link"></i></a>
</h3>
<p>Une façon simple et efficace de créer des données à ce stade est la package <code>MASS</code> dont un aperçu a été donné dans le chapitre sur les analyses de base.</p>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Création de la matrice de covariance pour p=3</span>
<span class="va">Sigma</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">s11</span>, <span class="va">s12</span>, <span class="va">s13</span>,
                 <span class="va">s12</span>, <span class="va">s22</span>, <span class="va">s23</span>,
                 <span class="va">s13</span>, <span class="va">s23</span>, <span class="va">s33</span><span class="op">)</span>, nrow <span class="op">=</span> <span class="fl">3</span>, ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>
<span class="co"># Création des données </span>
<span class="va">donnees</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, mu <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span>, Sigma <span class="op">=</span> <span class="va">Sigma</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>La matrice de covariance pour <span class="math inline">\(p=3\)</span> s’écrit comme suit.
<span class="math display">\[
\Sigma = \left(
\begin{array}{ccc}
\sigma_{1,1} &amp; \sigma_{1,2} &amp; \sigma_{1,3}\\
\sigma_{2,1} &amp; \sigma_{2,2} &amp; \sigma_{2,3}\\
\sigma_{3,1} &amp; \sigma_{3,2} &amp; \sigma_{2,3}
\end{array}
\right)
\]</span>
Il convient d’écrire <span class="math inline">\(\Sigma\)</span> (sigma majuscule) et <span class="math inline">\(\sigma\)</span> (sigma minuscule) plutôt que <span class="math inline">\(S\)</span>, car il s’agit de la matrice de covariance de la population. Le résultat de <code>S = cov(donnees)</code> est empirique et la notation <span class="math inline">\(S\)</span> est plus appropriée. Comme il y a <span class="math inline">\(p=3\)</span> variables dans la syntaxe, il faudra préalablement spécifier <span class="math inline">\(3*4/2 = 6\)</span> arguments :<span class="math inline">\(p = 3\)</span> variances <span class="math inline">\(\sigma_{1,1},\sigma_{3,3},\sigma_{3,3}\)</span> et <span class="math inline">\(3*2/2 =3\)</span> covariances <span class="math inline">\(\sigma_{1,2},\sigma_{1,3},\sigma_{2,3}\)</span>.</p>
</div>
<div id="la-matrice-de-corrélation" class="section level3" number="11.0.4">
<h3>
<span class="header-section-number">11.0.4</span> La matrice de corrélation<a class="anchor" aria-label="anchor" href="#la-matrice-de-corr%C3%A9lation"><i class="fas fa-link"></i></a>
</h3>
<p>Pour rappel, une matrice de corrélation est une matrice de covariance dont les variables ont été standardisées. Cela implique de transformer la matrice afin que toute la diagonale soit à l’unité, que toutes les variances soient égalent à 1. Cela permet d’avoir une interprétation <em>standardisée</em> des corrélations, car celles-ci sont indépendantes des métriques originales. Les autres éléments conceptuels de la matrice de covariance s’appliquent pour la matrice de corrélation.</p>
<p>Pour transformer la matrice de covariance en matrice de corrélation, trois techniques sont possibles.</p>
<p>La première est de standardise <span class="math inline">\(X\)</span> préalablement au calcul de la covariance. Comme il n’y a pas d’équivalent à <code><a href="https://rdrr.io/r/base/colSums.html">colMeans()</a></code> pour l’écart type, l’utilisation de <code>apply(X, MARGIN = 2, FUN = sd)</code> fera le travail. Cette ligne de syntaxe reproduit la même logique, mais pour l’écart type <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>. Textuellement, elle applique (<code><a href="https://rdrr.io/r/base/apply.html">apply()</a></code>) l’écart type (<code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>) pour chaque colonne <code>MARGIN = 2</code> à la matrice de données <code>X</code>.</p>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">X</span> <span class="op">=</span> <span class="op">(</span><span class="va">X</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">X</span>, MARGIN <span class="op">=</span> <span class="fl">2</span>, FUN <span class="op">=</span> <span class="va">sd</span><span class="op">)</span></code></pre></div>
<p>La deuxième méthode est de standardiser la matrice de covariance en termes d’algèbre matricielle, où <span class="math inline">\(S\)</span> est la matrice de covariance. Il faut extraire de la matrice les variances de la diagonale (avec la fonction mathématique <span class="math inline">\(\text{diag()}\)</span>), puis en faire la racine carrée pour obtenir des écarts types, puis en refaire une matrice carrée avec la fonction mathématique <span class="math inline">\(\text{diag()}\)</span> qu’il faut finalement inversé pour en faire une division.</p>
<p><span class="math display" id="eq:cov2cor">\[\begin{equation}
R = (\text{diag}(\sqrt{\text{diag}(S)})^{-1}) S (\text{diag}(\sqrt{\text{diag}(S)})^{-1})
\tag{11.6}
\end{equation}\]</span></p>
<p>En code <strong>R</strong>, l’équation <a href="r%C3%A9gression.html#eq:cov2cor">(11.6)</a> se traduit ainsi.</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">R</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">S</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">S</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="va">S</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Lorsqu’une matrice est passée comme argument à <code><a href="https://rdrr.io/r/base/diag.html">diag()</a></code>, elle extrait les éléments de la diagonale pour en faire un vecteur. Si un vecteur est passé en argument, alors <code><a href="https://rdrr.io/r/base/diag.html">diag()</a></code> retourne une matrice avec les éléments du vecteur en diagonale. La fonction <code><a href="https://rdrr.io/r/base/solve.html">solve()</a></code> calcule l’inverse d’une matrice, comme l’utilisateur pourrait attendre de <span class="math inline">\(X^{-1}\)</span>. Il s’agit certainement de l’aspect le plus biscornu de <strong>R</strong>. Enfin, l’opérateur <code>%*%</code> est le produit matriciel.</p>
<p>La troisième est d’utiliser la fonction de base <code><a href="https://rdrr.io/r/stats/cor.html">cov2cor()</a></code> pour transformer la matrice de covariance en matrice de corrélation, ce qui est plus simple et plus rapide que la deuxième option, mais qui cache ce qui se réalise.</p>
</div>
<div id="la-régression" class="section level2" number="11.1">
<h2>
<span class="header-section-number">11.1</span> La régression<a class="anchor" aria-label="anchor" href="#la-r%C3%A9gression"><i class="fas fa-link"></i></a>
</h2>
<p>Pour l’instant, des rudiments de la covariance et de la corrélation ont été présentés dans le but d’introduire graduellement l’algèbre matricielle. L’objectif étant atteint, le regard portera sur la régression en tant que moyen de prédire une variable <span class="math inline">\(y\)</span> à partir d’un ensemble de variables <span class="math inline">\(X\)</span>.</p>
<p>Quelle est la différence entre les analyses de covariance et corrélation comparativement à l’analyse de régression? Bien que la logique sous-jacente soit très similaire, il faut maintenant déterminer une variable <em>différente</em> de l’autre, c’est-à-dire une variable dépendante. Les autres sont des variables indépendantes. Les variables indépendantes prédisent la variable dépendante un peu comme dans un modèle <em>déterministe</em>, il faut décider de la cause (variables indépendantes) et l’effet (variable dépendante), ce dernier étant généré par les premiers.</p>
<p>Plutôt que de traiter chaque paire de variable comme c’était le cas avec l’analyse de corrélation, la régression correspond à étudier la relation entre la variable dépendante et toutes les autres, et ce, simultanément. Ainsi, les variables indépendantes sont contrôlées entre elles pour évaluer leur effet sur la variable dépendante et un modèle de prédiction plus juste est obtenu (autant que faire ce peut avec modèle statistique).</p>
<div id="le-modèle-de-régression-simple" class="section level3" number="11.1.1">
<h3>
<span class="header-section-number">11.1.1</span> Le modèle de régression simple<a class="anchor" aria-label="anchor" href="#le-mod%C3%A8le-de-r%C3%A9gression-simple"><i class="fas fa-link"></i></a>
</h3>
<p>L’équation pour un modèle de régression simple se résume en un cas bivarié, soit la prédiction de <span class="math inline">\(y\)</span> par une seule variable <span class="math inline">\(x\)</span>.</p>
<p><span class="math display" id="eq:modlin">\[\begin{equation}
y = \beta_0 + \beta_1 x + \epsilon_y
\tag{11.7}
\end{equation}\]</span></p>
<p>Dans ce modèle, <span class="math inline">\(y\)</span> est la variable prédite, <span class="math inline">\(x\)</span> est le seul prédicteur, <span class="math inline">\(\beta_0\)</span> est l’ordonnée à l’origine, <span class="math inline">\(\beta_1\)</span> est le coefficient de régression et <span class="math inline">\(\epsilon_y\)</span>, l’erreur dans la variable <span class="math inline">\(y\)</span> indépendante (non corrélée, ni fonctionnelement liée) de <span class="math inline">\(x\)</span>.</p>
</div>
<div id="création-de-données-1" class="section level3" number="11.1.2">
<h3>
<span class="header-section-number">11.1.2</span> Création de données<a class="anchor" aria-label="anchor" href="#cr%C3%A9ation-de-donn%C3%A9es-1"><i class="fas fa-link"></i></a>
</h3>
<p>Une façon simple de créer des données en fonction d’un modèle linéaire plutôt qu’à partir de la matrice de corrélation (comme ce fut le case jusqu’à présent) est de reprendre l’équation <a href="r%C3%A9gression.html#eq:modlin">(11.7)</a> et de spécifier les paramètres libre. D’abord, il faut remplacer les paramètres du modèle par des valeurs, <span class="math inline">\(beta_0\)</span>, <span class="math inline">\(beta_1\)</span>, et ensuite, créer deux variables aléatoires de taille <span class="math inline">\(n\)</span> (la taille d’échantillon), une première pour <span class="math inline">\(x\)</span> et une seconde pour <span class="math inline">\(\epsilon_y\)</span>. Les hypothèses sous-jacentes aux modèles linéaires assument généralement que la l’erreur (<span class="math inline">\(\epsilon\)</span>) est distribuée normalement (avec implicitement une moyenne de 0), la fonction <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> pourra jouer le rôle. Pour <span class="math inline">\(x\)</span>, il n’y a pas de distribution à respecter, mais une distribution normale fait très bien l’affaire. Voici un exemple de code <strong>R</strong>.</p>
<div class="sourceCode" id="cb139"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># En spécifiant une taille d'échantillon très grande,</span>
<span class="co"># l'erreur échantillonnalle est considérablement réduite.</span>
<span class="co"># Valeurs choisies par l'utilisateur</span>
<span class="va">n</span> <span class="op">=</span> <span class="fl">10000</span> <span class="co"># Taille d'échantillon</span>
<span class="va">beta0</span> <span class="op">=</span> <span class="fl">5</span> <span class="co"># Les betas</span>
<span class="va">beta1</span> <span class="op">=</span> <span class="fl">1</span>
<span class="co"># Deux variables aléatoires tirées de distributions normales.</span>
<span class="co"># Les moyennes sont nulles et </span>
<span class="co"># les écarts types sont spécifiés par l'utilisateur.</span>
<span class="va">x</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>
<span class="va">e.y</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, sd <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>
<span class="co"># Création de la variable dépendante</span>
<span class="va">y</span> <span class="op">=</span> <span class="va">beta0</span> <span class="op">+</span> <span class="va">beta1</span> <span class="op">*</span> <span class="va">x</span> <span class="op">+</span> <span class="va">e.y</span></code></pre></div>
<p>Si l’utilisateur souhaite ajouter une autre variable, il lui suffit d’ajouter un <span class="math inline">\(\beta\)</span> supplémentaire et de créer une autre variable aléatoire</p>
<p>Cette méthode de création de données possède toutefois des limites. Principalement, elle ne spécifie pas les propriétés statistiques désirables, par exemple, la corrélation entre les variables est évacuée. Quelle est la corrélation entre <code>x</code>et <code>y</code> dans l’exemple précédent? Il est bien sûr possible de déterminer ces valeurs pour la population a posteriori. Il faut résoudre l’équation <a href="r%C3%A9gression.html#eq:eqrho">(11.8)</a>.</p>
<p><span class="math display" id="eq:eqrho">\[\begin{equation}
\rho_{x,y} = \beta_1 \frac{\sigma_x}{\sigma_y}
\tag{11.8}
\end{equation}\]</span></p>
<p>Certaines valeurs sont déjà connues, car spécifiées par l’utilisateur, <span class="math inline">\(\beta_1 = 1\)</span> et <span class="math inline">\(\sigma_x = 1\)</span>. Qu’en est-il de <span class="math inline">\(\sigma_y\)</span>? L’utilisateur n’a pas spécifié la valeur de la variance de <span class="math inline">\(y\)</span>, il a plutôt choisi la valeur de la variance de l’erreur résiduelle, <span class="math inline">\(\sigma^2_{\epsilon_y}\)</span>. La loi de la somme des variances permettra de calculer cette valeur. Pour le lecteur intéressé, les réponses sont <span class="math inline">\(\sigma^2_y = \beta_1^2\sigma^2_x+\sigma^2_{\epsilon_y} = 10\)</span> et donc <span class="math inline">\(\rho_{x,y} = \frac{\beta_1 \sigma_x}{\sigma_y} = 0.316\)</span>.</p>
<p>La limite liée à la méthode de création de données est maintenant flagrante. En plus de ne pas connaître la corrélation entre les variables, la variance de <span class="math inline">\(y\)</span> n’est pas connue a priori. La stratégie de spécification est ainsi de choisir des valeurs et d’espérer qu’elles soient conformes aux attentes. Pire, s’il y avait plusieurs variables indépendantes, elles seraient toutes non corrélées entre elles, alors que l’utilisateur pourrait vouloir autrement, mais cette première technique ne le permet pas.</p>
<p>Pour l’utilisateur qui crée son jeu de données, ces caractéristiques sont souvent plus essentielles que de spécifier à l’avance la variance résiduelle. Pour résoudre cette situation, la solution est de spécifier un modèle standardisé, puis de le <em>déstandardiser</em> (ajouté des moyennes et des variances a posteriori).</p>
<p>La philosophie de modélisation de cet ouvrage repose sur l’idée selon laquelle, un modèle doit être standardisé au départ puis <em>déstandardisé</em>. Cette logique ne se prêtera pas à tous les contextes, pour certains la difficulté sera immense, pour d’autres, cela ne respectera pas les objectifs. En partant d’un modèle standardisé toutefois, la matrice de corrélation est connue à l’avance et la variance est spécifiée directement par l’utilisateur. Les tailles d’effets attendues sont également assurées. Il suffit de dériver la variance résiduelle du modèle plutôt que de la spécifier.</p>
<p>En assumant un modèle linéaire,</p>
<p><span class="math display" id="eq:modling">\[\begin{equation}
y = \beta_0 + \beta_1 x_1 + ... +\beta_k x_k + \epsilon_y
\tag{11.9}
\end{equation}\]</span></p>
<p>où l’équation <a href="r%C3%A9gression.html#eq:modling">(11.9)</a> correspond à la généralisation de l’équation <a href="r%C3%A9gression.html#eq:modlin">(11.7)</a> pour <span class="math inline">\(k\)</span> variables indépendantes, il est possible d’isoler <span class="math inline">\(\epsilon_y\)</span>. La variance se calcule alors comme l’équation <a href="r%C3%A9gression.html#eq:emat">(11.10)</a>, pour le cas générale.</p>
<p><span class="math display" id="eq:emat">\[\begin{equation}
\sigma^2_{\epsilon_y} = \sigma^2_y - B^{\prime}RB
\tag{11.10}
\end{equation}\]</span></p>
<p>où <span class="math inline">\(R\)</span> est la matrice de corrélation et <span class="math inline">\(B\)</span> est le vecteur contenant tous les <span class="math inline">\(\beta\)</span> standardisés. Pour assurer un scénario standardisé <span class="math inline">\(\sigma^2_y = 1\)</span>. La seule condition sous-jacente à l’équation <a href="r%C3%A9gression.html#eq:emat">(11.10)</a> est de s’assurer que <span class="math inline">\(\sigma^2_{\epsilon_y} &gt; 0\)</span>, c’est-à-dire en vérifiant que <span class="math inline">\(B^{\prime}RB &lt; \sigma^2_y\)</span>, autrement la variance est négative, ce qui est impossible. En termes de syntaxe <strong>R</strong>, l’équation <a href="r%C3%A9gression.html#eq:emat">(11.10)</a> correspond à ceci.</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Cacluler la variance de epsilon</span>
<span class="va">var_e</span> <span class="op">=</span> <span class="va">var_y</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">B</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">R</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">B</span></code></pre></div>
<p>L’avantage de cette technique est (a) de pouvoir spécifier les corrélations entre les variables indépendantes avec la matrice <span class="math inline">\(R\)</span>; (b) de déterminer à l’avance la variance de <span class="math inline">\(y\)</span> et (c) que le vecteur <span class="math inline">\(B\)</span> contient les <span class="math inline">\(\beta\)</span> standardisés qui sont dans ce contexte les corrélations partielles qui relient chacune des variables indépendantes à la variable dépendante (des tailles d’effet) en contrôlant pour chacune d’elles.</p>
<p>L’utilisateur crée par la suite les données en spécifiant le vecteur <span class="math inline">\(B\)</span> et en créant une variable basée sur la matrice de corrélation. Voici un exemple pour <span class="math inline">\(k=3\)</span> variables centrées suivant une distribution normale multivariée avec la matrice de corrélation <span class="math inline">\(R\)</span>.</p>
<p><span class="math display">\[
R= \left(
\begin{array}{ccc}
1 &amp; .2 &amp; .3\\
.2 &amp; 1 &amp; .1\\
.3 &amp; .1 &amp; 1
\end{array}
\right)
\]</span>
Une fois les données de <span class="math inline">\(X\)</span> créées, avec la fonction <code><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">MASS::mvrnorm()</a></code>, comme il a été fait précédemment, il suffit de multiplier <span class="math inline">\(X\)</span> avec <span class="math inline">\(B\)</span> et d’ajouter la variable aléatoire <span class="math inline">\(\epsilon_y\)</span> avec la variance appropriée pour obtenir la variable dépendante <span class="math inline">\(y\)</span>.</p>
<div class="sourceCode" id="cb141"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">42</span><span class="op">)</span>  <span class="co"># Pour reproductibilité</span>
<span class="va">n</span> <span class="op">=</span> <span class="fl">1000</span>      <span class="co"># Taille d'échantillon</span>
<span class="va">k</span> <span class="op">=</span> <span class="fl">3</span>         <span class="co"># Nombre de variables indépendantes</span>

<span class="co"># Matrice de corrélation</span>
<span class="va">R</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">.2</span>, <span class="fl">.3</span>,
             <span class="fl">.2</span>, <span class="fl">1</span>, <span class="fl">.1</span>,
             <span class="fl">.3</span>, <span class="fl">.1</span>, <span class="fl">1</span><span class="op">)</span>, <span class="va">k</span>, <span class="va">k</span><span class="op">)</span>
<span class="co"># Moyennes</span>
<span class="va">mu</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>, <span class="va">k</span><span class="op">)</span>

<span class="co"># Choix des betas standardisés</span>
<span class="va">B</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>beta1 <span class="op">=</span> <span class="fl">.2</span>, beta2 <span class="op">=</span> <span class="op">-</span><span class="fl">.5</span>, beta3 <span class="op">=</span> <span class="fl">.3</span><span class="op">)</span>

<span class="co">#variance de epsilon</span>
<span class="va">var_e</span> <span class="op">=</span> <span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">B</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">R</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">B</span>

<span class="co"># Créations des variables aléatoires</span>
<span class="va">X</span> <span class="op">=</span> <span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/mvrnorm.html">mvrnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, mu <span class="op">=</span> <span class="va">mu</span>, Sigma <span class="op">=</span> <span class="va">R</span><span class="op">)</span>
<span class="va">e</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="va">n</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">var_e</span><span class="op">)</span><span class="op">)</span>
<span class="co"># Création de la variable dépendante</span>
<span class="va">y</span> <span class="op">=</span> <span class="va">X</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">B</span> <span class="op">+</span> <span class="va">e</span>

<span class="co"># Création du jeu de données</span>
<span class="va">jd</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">y</span>, X <span class="op">=</span> <span class="va">X</span><span class="op">)</span>

<span class="co"># Quelques vérifications</span>
<span class="co"># Les données</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">jd</span><span class="op">)</span>
<span class="co">#&gt;        y    X.1    X.2     X.3</span>
<span class="co">#&gt; 1  0.635 -0.956 -2.567  0.3239</span>
<span class="co">#&gt; 2 -0.264  0.672 -0.172  0.5200</span>
<span class="co">#&gt; 3  0.341  0.885 -1.369 -0.6387</span>
<span class="co">#&gt; 4 -0.602  0.778 -1.104 -1.2678</span>
<span class="co">#&gt; 5  0.401  0.360  0.286 -1.4336</span>
<span class="co">#&gt; 6 -1.076 -0.210  0.621 -0.0399</span>
<span class="co"># La matrice de corrélation entre les variables indépendantes</span>
<span class="co"># Très près des valeurs choisies à la troisième décimale</span>
<span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span>
<span class="co">#&gt;       [,1]  [,2]  [,3]</span>
<span class="co">#&gt; [1,] 1.000 0.188 0.279</span>
<span class="co">#&gt; [2,] 0.188 1.000 0.136</span>
<span class="co">#&gt; [3,] 0.279 0.136 1.000</span>
<span class="co"># La variance de y (encore une fois très près)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span>
<span class="co">#&gt;      [,1]</span>
<span class="co">#&gt; [1,] 1.03</span></code></pre></div>
<p>Maintenant, il est possible de <em>déstandardisé</em> <code>X</code> et <code>y</code> en additionnant des moyennes ou multipliant par des écarts types à chaque variable.</p>
</div>
</div>
<div id="lanalyse-de-régression" class="section level2" number="11.2">
<h2>
<span class="header-section-number">11.2</span> L’analyse de régression<a class="anchor" aria-label="anchor" href="#lanalyse-de-r%C3%A9gression"><i class="fas fa-link"></i></a>
</h2>
<p>Lorsque le jeu de données est obtenu, il est temps de procéder à l’analyse de régression. Essentiellement, l’analyse de régression produit à peu près ceci (mais en algèbre matricielle).</p>
<p>Pour aider la compréhension, voici une explication avec le modèle linéaire simple assumant des variables centrées. Le modèle correspond à</p>
<p><span class="math display">\[
y = \beta x
\]</span></p>
<p>où l’erreur, <span class="math inline">\(\epsilon_y\)</span> n’est pas explicitée. Il faut isoler <span class="math inline">\(\beta\)</span> afin de l’estimer, soit l’opération suivante,</p>
<p><span class="math display">\[
\beta = \EX(\frac{y}{x})
\]</span></p>
<p>où le symbole <span class="math inline">\(\EX\)</span> signifie l’espérance (la moyenne). En multipliant par <span class="math inline">\(\frac{x}{x}\)</span> de chaque côté de l’équation, cela produit l’équation suivante.</p>
<p><span class="math display" id="eq:beta2">\[\begin{equation}
\beta = \EX(\frac{xy}{xx}) = \frac{\sigma_{xy}}{\sigma^2_x}
\tag{11.11}
\end{equation}\]</span></p>
<p>Dans l’équation <a href="r%C3%A9gression.html#eq:beta2">(11.11)</a>, le numérateur sera rapidement reconnu comme la covariance et au dénominateur la variance de <span class="math inline">\(X\)</span>. Comment généralisé pour <span class="math inline">\(k\)</span> variables? En algèbre matricielle et dans la mesure où les variables contenues dans <span class="math inline">\(X\)</span> sont centrées, cela revient au même que de calculer l’équation <a href="r%C3%A9gression.html#eq:beta">(11.12)</a>.</p>
<p><span class="math display" id="eq:beta">\[\begin{equation}
\hat{B} = (X^{\prime} X)^{-1} X^{\prime} y
\tag{11.12}
\end{equation}\]</span></p>
<p>Comme pour l’équation <a href="r%C3%A9gression.html#eq:beta2">(11.11)</a>, la composante <span class="math inline">\((X^{\prime} X)^{-1}\)</span> agit en dénominateur (par l’exposant <span class="math inline">\(-1\)</span>) et correspond à la matrice de variance-covariance des variables de <span class="math inline">\(X\)</span> ensemble, alors que <span class="math inline">\(X^{\prime} y\)</span> agit comme le numérateur, soit la covariance entre les variables de <span class="math inline">\(X\)</span> avec <span class="math inline">\(y\)</span>.</p>
<p>Pour l’erreur type, il s’agit de calculer ceci.</p>
<p><span class="math display">\[\begin{equation}
\text{var}(\hat{B}) = \sigma^2 \left(X^{\prime}X\right)^{-1}
\end{equation}\]</span></p>
<p>La racine carrée donne l’erreur type (<em>standard error</em>).</p>
<p>Le ratio <span class="math inline">\(\frac{B}{\text{se}_B} \sim t_{n-p-1}\)</span>, soit le quotient d’un estimateur par son erreur type, suit une distribution-<span class="math inline">\(t\)</span> avec <span class="math inline">\(n-p-1\)</span> degrés de liberté.</p>
<p>En syntaxe <strong>R</strong>, la régression s’écrit comme ceci.</p>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">regression</span> <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">y</span>, <span class="va">X</span><span class="op">)</span><span class="op">{</span>
  <span class="co"># Ajouter un intercepte</span>
  <span class="va">X</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span>intercept <span class="op">=</span> <span class="fl">1</span>, <span class="va">X</span><span class="op">)</span>
  <span class="va">B</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">y</span>
  <span class="va">var.e</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.html">var</a></span><span class="op">(</span><span class="va">y</span> <span class="op">-</span> <span class="va">X</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">B</span><span class="op">)</span> 
  <span class="va">se.B</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">var.e</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/diag.html">diag</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/solve.html">solve</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/r/base/matmult.html">%*%</a></span> <span class="va">X</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
  <span class="va">n</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>
  <span class="va">p</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">X</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>
  <span class="va">vt</span> <span class="op">=</span> <span class="va">B</span> <span class="op">/</span> <span class="va">se.B</span>
  <span class="va">vp</span> <span class="op">=</span> <span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="va">tv</span>, df <span class="op">=</span> <span class="va">n</span> <span class="op">-</span> <span class="va">p</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">*</span> <span class="fl">2</span>
  <span class="va">resultats</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Estimate <span class="op">=</span> <span class="va">B</span>, 
                         Std.Error <span class="op">=</span> <span class="va">se.B</span>, 
                         t.value <span class="op">=</span> <span class="va">vt</span>, 
                         p.value <span class="op">=</span> <span class="va">vp</span><span class="op">)</span> 
  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">resultats</span><span class="op">)</span>
<span class="op">}</span>  </code></pre></div>
<p>Le modèle linéaire peut aussi contenir des variables nominales dans la mesure où celle-ci sont transformées en données factices (<em>dummy coding</em>). En fait, une analyse de variance n’est au fond qu’une régression dans laquelle les variables nominales sont transformées en données factices, puis utilisées en variable indépendante. Les <span class="math inline">\(\beta\)</span> de la régression correspondent aux moyennes <span class="math inline">\(\mu\)</span>, si le participant appartient (1) à tel ou tel autre groupe ou (0) autrement. Bien que les logiciels produisent souvent des sorties statistiques différentes en fonction de l’analyse demandée, les mathématiques sous-jacentes sont les mêmes.</p>
<div id="conditions-dapplication-de-la-régression" class="section level3" number="11.2.1">
<h3>
<span class="header-section-number">11.2.1</span> Conditions d’application de la régression<a class="anchor" aria-label="anchor" href="#conditions-dapplication-de-la-r%C3%A9gression"><i class="fas fa-link"></i></a>
</h3>
<p>La régression possède quatre hypothèses sous-jacentes :</p>
<ul>
<li><p>La vraie relation est linéaire;</p></li>
<li><p>Les observations sont indépendantes.</p></li>
<li><p>Les résidus sont normalement distribués;</p></li>
<li><p>La variance résiduelle est homoscédastique.</p></li>
</ul>
<p>Les deux premiers points sont davantage méthodologiques que statistiques bien que leurs conséquences soient réelles. La relation entre les variables doit être linéaire. La régression tient compte des relations en ligne droite, si la relation entre deux variables suit une courbe, elle ne pourra être adéquatement analysée. La figure <a href="r%C3%A9gression.html#fig:courbe">11.3</a> montre trois relations possibles entre deux variables. Bien que la relation soit très forte, peu importe la forme de la relation (les données suivent un parton très évident), seule celle au centre (relation linéaire) donnera un résultat indiquant un lien fort existant. Il existe des techniques de transformation de données lorsque ce sera <em>théoriquement</em> justifié. La relation quantitative entre l’âge et la quantité de rapport sexuel est un exemple de relation non linéaire : elle débute à l’adolescence, atteint son apogée à l’âge de jeune adulte, puis décroît progressivement. La seconde hypothèse est que les unités d’observation doivent être indépendantes. Techniquement, chaque unité devrait avoir une chance égale et indépendante d’être choisie. La régression est robuste à ce genre de violation, mais il faut toujours conserver cette idée en tête lorsque le devis d’étude est conceptualisé et lors des analyses. Les élèves dans une même salle de classe ne sont techniquement pas indépendants puisqu’ils sont tous corrélés. Ils ont le même enseignant, les mêmes pairs, les locaux, etc., des variables qui peuvent toutes à leur façon avoir des effets sur les comportements des enfants. Dans ce cas, recourir à des analyses multiniveaux sera la seule possibilité pour tenir compte de cette violation et bien représenter les modèles. Un autre exemple est la corrélation entre différents temps de mesure sur une même unité (qui est corrélée avec elle-même). Dans ce cas, ce sera des analyses pour des devis temporels (les analyses multiveaux peuvent également tenir compte du temps).</p>
<p>Les deux autres considérations, qui sont elles d’ordre statistique, concernent les résidus (l’écart entre la prédiction et les valeurs réelles de <span class="math inline">\(y\)</span>). Comme il a été mentionné dans la création de données pour la régression, les distributions des variables n’a pas être normales; elles peuvent suivre différentes distributions de probabilités. Par contre, l’erreur, elle, doit être normales distribuées, car il s’agit d’une hypothèse assumée de l’estimation des moindres carrés. La dernière hypothèse concerne la variance résiduelle homoscédastique, c’est-à-dire que l’écart entre les résidus et les valeurs prédites restent <em>constantes,</em> peu importe le niveau sur la droite de régression. Si ce n’est pas le cas pour l’une ou l’autre, c’est qu’une variable a vraisemblablement été négligée ou qu’une des relations n’est pas linéaire avec une des variables indépendantes.</p>
<pre><code>#&gt; `geom_smooth()` using formula 'y ~ x'</code></pre>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:courbe"></span>
<img src="06-Regression_files/figure-html/courbe-1.png" alt="Différentes formes de relation" width="80%" height="80%"><p class="caption">
Figure 11.3: Différentes formes de relation
</p>
</div>
</div>
<div id="lanalyse-de-régression-1" class="section level3" number="11.2.2">
<h3>
<span class="header-section-number">11.2.2</span> L’analyse de régression<a class="anchor" aria-label="anchor" href="#lanalyse-de-r%C3%A9gression-1"><i class="fas fa-link"></i></a>
</h3>
<p><strong>R</strong> de base offre la fonction <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> pour <em>linear model</em> (modèle linéaire) afin de réaliser une régression. Pour réaliser l’analyse, deux éléments sont primordiaux : le jeu de données et le modèle. Le jeu de données est assez explicite. Le modèle linéaire est quant à lui déjà représenté par l’équation <a href="r%C3%A9gression.html#eq:modling">(11.9)</a>.</p>
<p>Pour écrire le modèle en syntaxe <strong>R</strong>, il faut remplacer les <span class="math inline">\(x\)</span> par le nom des variables dans le jeu de données, utiliser le <code>~</code> (tilde) pour délimiter les variables dépendantes à gauche des variables indépendantes à droite. Les variables indépendantes sont délimitées, comme dans l’équation <a href="r%C3%A9gression.html#eq:modling">(11.9)</a>, par des signes d’addition <code>+</code>. Il est aussi de définir des effets d’interaction (modération) avec le signe de multiplication <code>*</code>. Les symboles <code>-</code> (soustraction) et <code>/</code> (division) ne fonctionnent pas. L’intercepte (<span class="math inline">\(\beta_0\)</span>) est ajouté par défaut. Enfin, cette équation doit ensuite être mis entre guillemets, <code>formula = "y ~ x1 + x2 + x3"</code> pour indiquer qu’il s’agit de texte.</p>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Créer un jeu de données à partir des variables de la syntaxe précédente</span>
<span class="va">res.lm</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">y</span> <span class="op">~</span> <span class="va">X.1</span> <span class="op">+</span> <span class="va">X.2</span> <span class="op">+</span> <span class="va">X.3</span>, data <span class="op">=</span> <span class="va">jd</span><span class="op">)</span>
<span class="co"># Les résultats</span>
<span class="va">res.lm</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Call:</span>
<span class="co">#&gt; lm(formula = y ~ X.1 + X.2 + X.3, data = jd)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Coefficients:</span>
<span class="co">#&gt; (Intercept)          X.1          X.2          X.3  </span>
<span class="co">#&gt;     -0.0171       0.2139      -0.5520       0.3095</span>
<span class="co"># Sommaire des résultats</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">res.lm</span><span class="op">)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Call:</span>
<span class="co">#&gt; lm(formula = y ~ X.1 + X.2 + X.3, data = jd)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Residuals:</span>
<span class="co">#&gt;     Min      1Q  Median      3Q     Max </span>
<span class="co">#&gt; -2.5227 -0.5546 -0.0119  0.5513  2.5762 </span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Coefficients:</span>
<span class="co">#&gt;             Estimate Std. Error t value Pr(&gt;|t|)    </span>
<span class="co">#&gt; (Intercept)  -0.0171     0.0253   -0.68      0.5    </span>
<span class="co">#&gt; X.1           0.2139     0.0266    8.03  2.7e-15 ***</span>
<span class="co">#&gt; X.2          -0.5520     0.0258  -21.42  &lt; 2e-16 ***</span>
<span class="co">#&gt; X.3           0.3095     0.0263   11.76  &lt; 2e-16 ***</span>
<span class="co">#&gt; ---</span>
<span class="co">#&gt; Signif. codes:  </span>
<span class="co">#&gt; 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Residual standard error: 0.8 on 996 degrees of freedom</span>
<span class="co">#&gt; Multiple R-squared:  0.383,  Adjusted R-squared:  0.381 </span>
<span class="co">#&gt; F-statistic:  206 on 3 and 996 DF,  p-value: &lt;2e-16</span></code></pre></div>
<p>Pour ajouter une variable il suffit de <code>VD ~ VI1 + VI2</code>; pour ajouter un effet d’interaction, il est possible de faire <code>VD ~ VI1 * VI2</code>. Pour ajouter une variable nominale (catégorielle), il suffit d’ajouter la variable comme n’importe quelles autres <code>x</code>, mais en s’assurant bien qu’elle soit désignée comme un facteur dans le jeu de données. Si ce n’était pas le cas, la fonction <code><a href="https://rdrr.io/r/base/factor.html">as.factor()</a></code> devrait corriger la situation.</p>
<p>La fonction <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> en elle-même n’imprime que peut de résultats. Pour obtenir l’information complète, il faut requérir le sommaire avec la fonction <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>. Le sommaire des résultats contient toute l’information qu’un expérimentateur peut désirer. Il y a les coefficients de régression <code>Estimate</code>, leur erreur standard <code>Std. Error</code>, leur valeur-<span class="math inline">\(t\)</span> <code>t value</code> et leur valeur-<span class="math inline">\(p\)</span> <code>Pr(&gt;|t|)</code>. Tout cela peut être extrait avec <code>summary(res.lm)$...</code> en remplaçant <code>...</code> par les éléments désirés. Au-dessous de la sortie imprimée, il y a également le coefficient de détermination (<span class="math inline">\(R^2\)</span>, <code>R-squared</code>), les degrés de liberté et la valeur-<span class="math inline">\(p\)</span> associé au modèle.</p>
<p>Un manuscrit pourrait rapport les résultats ainsi. Le modèle tester obtient un coefficient de détermination de <span class="math inline">\(R^2(996) = 0.383, p &lt; .001\)</span>. Les trois prédicteurs sont liés significativement à la variable dépendante, respectivement <span class="math inline">\(X_1: \beta_1 = 0.214, p = &lt; .001\)</span>, <span class="math inline">\(X_2: \beta_2 = 0.214, p = &lt; .001\)</span>, <span class="math inline">\(X_3: \beta_3 = 0.31, p = &lt; .001\)</span>. Évidemment, comme l’exemple est artificiel, il y a peu de chose à dire sans devoir fabriquer de toutes pièces des interprétations alambiquées bien que cela fût fort bénéfique pour la carrière de certains psychanalystes.</p>
<p>Pour vérifier la qualité des résultats, il faut vérifier la distribution des résidus. Pour ce faire, il faut extraire les résidus et les valeurs prédites. Pour la création de graphiques, il est plus simple d’ajouter ces scores au jeu de données. Les fonctions <code><a href="https://rdrr.io/r/stats/residuals.html">resid()</a></code> et <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> permettront d’extraire les résidus et les prédictions en y insérant comme argument le sommaire de la fonction <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> obtenu avec les données.</p>
<div class="sourceCode" id="cb145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ajouter les résidus et scores prédits à la base de données</span>
<span class="co"># avec la fonction `resid()`</span>
<span class="va">jd</span><span class="op">$</span><span class="va">residu</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">resid</a></span><span class="op">(</span><span class="va">res.lm</span><span class="op">)</span>
<span class="va">jd</span><span class="op">$</span><span class="va">predit</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">res.lm</span><span class="op">)</span></code></pre></div>
<p>Une fois, c’est valeur extraite, le package <code>ggplot2</code> permet de réaliser rapidement des graphiques, comme le diagramme de dispersion à la figure <a href="r%C3%A9gression.html#fig:respred">11.4</a> ou l’histogramme des résidus à la figure <a href="r%C3%A9gression.html#fig:reshist">11.5</a>. Dans les meilleures situations, les résidus seront distribués normalement dans l’histogramme et aucune tendance ne devrait être discernable dans le diagramme de dispersion. Si ce n’était pas le cas, il pourrait y avoir un problème à élucider, par exemple, une relation non linéaire imprévue. Les figures <a href="r%C3%A9gression.html#fig:respred">11.4</a> et <a href="r%C3%A9gression.html#fig:reshist">11.5</a> ne signale aucun problème, ce qui est attendu considérant la création des données employées.</p>
<div class="sourceCode" id="cb146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Diagramme de dispersion prédits par résidus</span>
<span class="va">jd</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">predit</span>, y <span class="op">=</span> <span class="va">residu</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> </code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:respred"></span>
<img src="06-Regression_files/figure-html/respred-1.png" alt="Relation entre prédicitons et résidus" width="75%" height="75%"><p class="caption">
Figure 11.4: Relation entre prédicitons et résidus
</p>
</div>
<div class="sourceCode" id="cb147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Histogramme des résidus</span>
<span class="va">jd</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">residu</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:reshist"></span>
<img src="06-Regression_files/figure-html/reshist-1.png" alt="Histogramme des résidus" width="75%" height="75%"><p class="caption">
Figure 11.5: Histogramme des résidus
</p>
</div>
<!-- # L'analyse de régression en modélisation par équations structurelles -->
<!-- # Exercices -->

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="exercice-analyse.html">Exercices</a></div>
<div class="next"><a href="cr%C3%A9er.html"><span class="header-section-number">12</span> Créer</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#r%C3%A9gression"><span class="header-section-number">11</span> Régression</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#illustration-de-la-covariance"><span class="header-section-number">11.0.1</span> Illustration de la covariance</a></li>
<li><a class="nav-link" href="#la-covariance-en-termes-dalg%C3%A8bre-matricielle"><span class="header-section-number">11.0.2</span> La covariance en termes d’algèbre matricielle</a></li>
<li><a class="nav-link" href="#cr%C3%A9ation-de-donn%C3%A9es"><span class="header-section-number">11.0.3</span> Création de données</a></li>
<li><a class="nav-link" href="#la-matrice-de-corr%C3%A9lation"><span class="header-section-number">11.0.4</span> La matrice de corrélation</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#la-r%C3%A9gression"><span class="header-section-number">11.1</span> La régression</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#le-mod%C3%A8le-de-r%C3%A9gression-simple"><span class="header-section-number">11.1.1</span> Le modèle de régression simple</a></li>
<li><a class="nav-link" href="#cr%C3%A9ation-de-donn%C3%A9es-1"><span class="header-section-number">11.1.2</span> Création de données</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#lanalyse-de-r%C3%A9gression"><span class="header-section-number">11.2</span> L’analyse de régression</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#conditions-dapplication-de-la-r%C3%A9gression"><span class="header-section-number">11.2.1</span> Conditions d’application de la régression</a></li>
<li><a class="nav-link" href="#lanalyse-de-r%C3%A9gression-1"><span class="header-section-number">11.2.2</span> L’analyse de régression</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/quantmeth/MQR/blob/master/06-Regression.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/quantmeth/MQR/edit/master/06-Regression.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Méthodes Quantitatives avec R</strong>" was written by P.-O. Caron. It was last built on 2022-05-19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
